name: scala-CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    name: ソースコードのフォーマット確認
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

      - name: Check formatting
        run: sbt scalafmtCheckAll

  cache-nix:
    name: nix依存関係のキャッシュ
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nix
        uses: cachix/install-nix-action@v25

      - name: setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: b4smt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      
      - name: generate processor
        run: make processor

      - name: upload processor source as artifact
        uses: actions/upload-artifact@v3
        with:
          name: processor
          path: processor/

      - name: make all
        run: make
      - name: make develop environment
        run: nix develop --profile develop-profile -c true

      - name: upload artifacts
        run: |
          nix path-info -r ./processor | cachix push b4smt
          nix path-info -r ./programs | cachix push b4smt
          nix path-info -r ./develop-profile | cachix push b4smt

  test-all:
    name: B4プロセッサのテスト
    timeout-minutes: 60
    needs: [cache-nix]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nix
        uses: cachix/install-nix-action@v25

      - name: setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: b4smt

      - name: test all
        run: make check
